/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_uid2_attestation_aws_NitroAttestation */

#ifndef _Included_com_uid2_attestation_aws_NitroAttestation
#define _Included_com_uid2_attestation_aws_NitroAttestation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_uid2_attestation_aws_NitroAttestation
 * Method:    generateAttestationRequestInternal
 * Signature: ([B[B[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_uid2_attestation_aws_NitroAttestation_generateAttestationRequestInternal
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
